# Generated by Django 4.2.7 on 2023-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
