# Generated by Django 4.2.7 on 2023-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapi', '0002_alter_education_grade_alter_education_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='grade',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='percentage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
