# Generated by Django 4.2.7 on 2023-11-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapi', '0003_alter_certification_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
